[env:why2025-carrier]
extra_scripts = bin/platformio-whybadge.py
extends = esp32c6_base
board = esp32-c6-devkitc-1
lib_deps =
  ${esp32c6_base.lib_deps}
  h2zero/NimBLE-Arduino@^2.3.6
build_flags =
  ${esp32c6_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32c6/diy/why2025_carrier
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DHAS_BLUETOOTH=1
  -DNIMBLE_TWO
  -DCONFIG_BT_NIMBLE_EXT_ADV=1
  -DCONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=2
  -DMESHTASTIC_EXCLUDE_WEBSERVER
  -DMESHTASTIC_EXCLUDE_MQTT
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER=1
build_unflags =
  -D HAS_BLUETOOTH
  -D MESHTASTIC_EXCLUDE_BLUETOOTH
  -D HAS_WIFI
board_build.partitions = partition-table-8MB.csv
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_ignore =
  NonBlockingRTTTL
  libpax